//
// Created by 朱原昊 on 2021/3/30.
//

#ifndef WIRELESS_CHARGING_SCHEME_SIMULATOR_CONFIG_H
#define WIRELESS_CHARGING_SCHEME_SIMULATOR_CONFIG_H
#define MU_RANGE_LOW 2.0
#define MU_RANGE_HIGH 6.0


#endif //WIRELESS_CHARGING_SCHEME_SIMULATOR_CONFIG_H
