//
// Created by 朱原昊 on 2021/2/2.
//

#ifndef WIRELESS_CHARGING_SCHEME_SIMULATOR_METRICS_TEST_H
#define WIRELESS_CHARGING_SCHEME_SIMULATOR_METRICS_TEST_H


class Metrics_test {
public:
   static int test();
};


#endif //WIRELESS_CHARGING_SCHEME_SIMULATOR_METRICS_TEST_H
